### ISSUE TITLE
Changes are not refreshing

### ISSUE THREAD

**Issue by HunterJS-bit** [tralves/nativescript-vue-webpack-template#7]
Hi I have a problem changes I made in any of files js or vue or css are not refreshing and not livesyncing the app.

**Comment by tralves** [comment]
That is a huge problem with this template, and one I don't know how to solve yet.

In Angular NS projects, they advice to only use web pack to bundle the final version of the app because 1) it takes some time and 2) NS may not deal well with incremental builds...

Still, I need to try it. Thanks for opening this Issue. I was about to add it too...

**Comment by NZX-DeSiGN** [comment]
Hi, I think we have a problem, nativescript-dev-webpack is not designed to be use in development, but at release time ...
See: NativeScript/nativescript-dev-webpack#165

**Comment by tralves** [comment]
Hi,
We got it to work in this other template: https://github.com/tralves/nativescript-vue-rollup-template

Check it out! The README.md shows how to use it.
